name: Create release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: min-editor-linux-x64
          - os: macOS-latest
            asset_name: min-editor-macos-aarch64
          - os: macOS-13
            asset_name: min-editor-macos-x64
          - os: windows-latest
            asset_name: min-editor-windows-x64
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: pkg
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: modules/bootstrap/build/distributions/*.zip

  create-release:
    permissions:
      contents: write
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: min-editor-*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: min-editor-*/*
